// This file is generated by tools/gen_types/generate-protocol-types.mjs.
// Do not edit directly.


export type MuesliBtCanonicalEventStreamEnvelopeMbtEvtV1 = ({
[k: string]: any
} & {
schema: "mbt.evt.v1"
contract_version: "1.0.0"
type: ("run_start" | "run_end" | "episode_begin" | "episode_end" | "bt_def" | "tick_begin" | "tick_end" | "tick_audit" | "tick_ok" | "tick_deadline_missed" | "gc_begin" | "gc_end" | "node_enter" | "node_exit" | "node_status" | "budget_warning" | "deadline_exceeded" | "bb_write" | "bb_delete" | "bb_snapshot" | "sched_submit" | "sched_start" | "sched_finish" | "sched_cancel" | "planner_call_start" | "planner_call_end" | "cap_call_start" | "cap_call_end" | "planner_v1" | "planner_timeout" | "vla_timeout" | "host_action_invalid" | "fallback_used" | "fallback_failed" | "late_result_dropped" | "cancel_acknowledged" | "cancel_late" | "vla_submit" | "vla_poll" | "vla_cancel" | "vla_result" | "async_cancel_requested" | "async_cancel_acknowledged" | "async_completion_dropped" | "error")
run_id: string
unix_ms: number
seq: number
tick?: number
data: {
[k: string]: any
}
})
