// This file is generated by tools/gen_types/generate-protocol-types.mjs.
// Do not edit directly.


/**
 * Canonical event stream payload for muesli-bt replay and monitoring.
 */
export type MbtEvtV1Event = (RunStartEvent | BtDefEvent | TickBeginEvent | TickEndEvent | NodeStatusEvent | BbWriteEvent | BbDeleteEvent | BbSnapshotEvent | SchedSubmitEvent | SchedStartEvent | SchedFinishEvent | SchedCancelEvent | PlannerV1Event | VlaSubmitEvent | VlaPollEvent | VlaCancelEvent | VlaResultEvent | ErrorEvent)
export type RunStartEvent = (EventBase & {
type?: "run_start"
data?: {
git_sha: string
host: string
tick_hz: number
tree_hash: string
backend?: string
}
[k: string]: any
})
export type EventType = ("run_start" | "bt_def" | "tick_begin" | "tick_end" | "node_status" | "bb_write" | "bb_delete" | "bb_snapshot" | "sched_submit" | "sched_start" | "sched_finish" | "sched_cancel" | "planner_v1" | "vla_submit" | "vla_poll" | "vla_cancel" | "vla_result" | "error")
export type BtDefEvent = (EventBase & {
type?: "bt_def"
data?: {
nodes: BtNode[]
edges: BtEdge[]
dsl?: string
}
[k: string]: any
})
export type TickBeginEvent = (EventBase & {
type?: "tick_begin"
data?: {
wall_ms?: number
}
[k: string]: any
})
export type TickEndEvent = (EventBase & {
type?: "tick_end"
data?: {
wall_ms?: number
}
[k: string]: any
})
export type NodeStatusEvent = (EventBase & {
type?: "node_status"
data?: {
node_id: string
status: Status
outcome?: Outcome
duration_ms?: number
message?: string
}
[k: string]: any
})
export type Status = ("idle" | "running" | "success" | "failure" | "skipped")
export type Outcome = ("ok" | "error" | "timeout" | "cancelled")
export type BbWriteEvent = (EventBase & {
type?: "bb_write"
data?: {
key: string
digest: string
preview?: string
}
[k: string]: any
})
export type BbDeleteEvent = (EventBase & {
type?: "bb_delete"
data?: {
key: string
reason?: string
}
[k: string]: any
})
export type BbSnapshotEvent = (EventBase & {
type?: "bb_snapshot"
data?: {
values: {
[k: string]: BlackboardValue
}
}
[k: string]: any
})
export type SchedSubmitEvent = (EventBase & {
type?: "sched_submit"
data?: {
job_id: string
node_id?: string
queue?: string
}
[k: string]: any
})
export type SchedStartEvent = (EventBase & {
type?: "sched_start"
data?: {
job_id: string
worker?: string
}
[k: string]: any
})
export type SchedFinishEvent = (EventBase & {
type?: "sched_finish"
data?: {
job_id: string
outcome: Outcome
duration_ms?: number
}
[k: string]: any
})
export type SchedCancelEvent = (EventBase & {
type?: "sched_cancel"
data?: {
job_id: string
reason?: string
}
[k: string]: any
})
export type PlannerV1Event = (EventBase & {
type?: "planner_v1"
data?: {
budget_ms: number
time_used_ms: number
confidence: number
summary?: string
}
[k: string]: any
})
export type VlaSubmitEvent = (EventBase & {
type?: "vla_submit"
data?: {
request_id: string
service: string
prompt?: string
}
[k: string]: any
})
export type VlaPollEvent = (EventBase & {
type?: "vla_poll"
data?: {
request_id: string
status?: Status
}
[k: string]: any
})
export type VlaCancelEvent = (EventBase & {
type?: "vla_cancel"
data?: {
request_id: string
reason?: string
}
[k: string]: any
})
export type VlaResultEvent = (EventBase & {
type?: "vla_result"
data?: {
request_id: string
outcome: Outcome
summary?: string
}
[k: string]: any
})
export type ErrorEvent = (EventBase & {
type?: "error"
data?: {
severity: Severity
message: string
code?: string
node_id?: string
}
[k: string]: any
})
export type Severity = ("info" | "warning" | "error" | "fatal")

export interface EventBase {
schema: "mbt.evt.v1"
type: EventType
run_id: string
unix_ms: number
seq: number
tick?: number
data: {
[k: string]: any
}
}
export interface BtNode {
id: string
name: string
kind: string
parent_id?: string
source?: string
}
export interface BtEdge {
from: string
to: string
}
export interface BlackboardValue {
digest: string
preview?: string
}
